import tkinter as tk

def saludar():
    nombre = entrada_nmbr.get()
    edad = entrada_edd.get()
    etiqueta_resultado.config(text=f"Hola {nombre}, tienes: {edad} años")
ventana = tk.Tk()
ventana.title("Mi primera app gráfica")
ventana.geometry("500x500")
ventana.configure(bg="blue")
etiqueta_nmbr = tk.Label(ventana, text="escribe tu nombre:", bg="beige")
etiqueta_nmbr.pack()
entrada_nmbr = tk.Entry(ventana)
entrada_nmbr.pack()
etiqueta_edd = tk.Label (ventana, text="escribe tu edad:", bg="gray")
etiqueta_edd.pack()
entrada_edd = tk.Entry(ventana)
entrada_edd.pack()
boton = tk.Button(ventana, text="Mostrar saludo", command=saludar)
boton.pack()
etiqueta_resultado = tk.Label(ventana, text="", bg="white")
etiqueta_resultado.pack()
nombre = tk.Label(ventana, text="Zempoalteca Valerdi Erik Alonso", fg="black", bg="blue")
nombre.place(relx=1.0, rely=1.0, x=-160, y=-200, anchor="se")
ventana.mainloop()
