import tkinter as tk

def saludar():
    nombre = entrada_nmbr.get()
    edad = entrada_edd.get()
    etiqueta_resultado.config(text=f"Hola {nombre}, tu edad es: {edad} años")
ventana = tk.Tk()
ventana.title("Mi primera app gráfica")
ventana.geometry("400x200")
etiqueta_nmbr = tk.Label(ventana, text="escribe tu nombre:")
etiqueta_nmbr.pack()
entrada_nmbr = tk.Entry(ventana)
entrada_nmbr.pack()
etiqueta_edd = tk.Label (ventana, text="escribe tu edad:")
etiqueta_edd.pack()
entrada_edd = tk.Entry(ventana)
entrada_edd.pack()
boton = tk.Button(ventana, text="Mostrar saludo", command=saludar)
boton.pack()
etiqueta_resultado = tk.Label(ventana, text="")
etiqueta_resultado.pack()
ventana.mainloop()
